### ISSUE TITLE
Theater Production Subsites

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/theater-production-subsites#3]
```[tasklist]
### Tasks
- [ ] #1
- [ ] https://github.com/figuren-theater/theater-production-subsites/issues/4
- [ ] https://github.com/figuren-theater/theater-production-subsites/issues/6
- [ ] https://github.com/figuren-theater/theater-production-subsites/issues/12
```
